01-11
siriusdevs/oop_7-1_2022 pull request #10
Opened 2022-11-07 06:55 UTC by annashutova

2022-11-07 07:43 UTC, annashutova commented
@siriusdevs, проверьте домашечку, пожалуйста)

2022-11-09 19:40 UTC, siriusdevs requested changes

2022-11-09 19:40 UTC, siriusdevs commented on hw1/figures.py
> +    """Class of triangle's methods.
class of methods? :smiley:

2022-11-09 19:40 UTC, siriusdevs commented on hw1/figures.py
> +    def area(self) -> float:
не округляете? будут проблемы с "неточными вычислениями", мы говорили об этом на паре. нужно округлять до 2 знака после точки, например

2022-11-09 19:40 UTC, siriusdevs commented on hw1/figures.py
> +        return 2 * pi * self.radius
то же самое с округлением везде

2022-11-09 19:40 UTC, siriusdevs commented on hw1/test_figures.py
> +    assert Triangle(side1, side2, side3).area() == pytest.approx(answer, rel=APPROX_VALUE)
ну штош.. это тоже вариант..
но приятно ли вам думать, что периметр треугольника 0.2, 0.2, 0.2 это 0.6000000000000001 ?
если вы с этим спите по ночами, то оставим

2022-11-09 19:40 UTC, siriusdevs commented on hw1/test_figures.py
> +    assert triangle.side3 == side3
Проблема с такой записью в том, что если первый  assert будет False, остальные не выполнятся. в данном случае это ОК и даже правильно, но на будущее обязательно имейте ввиду!

2022-11-20 15:21 UTC, siriusdevs approved these changes

2022-11-20 15:21 UTC, merged