добавлено дз за 01-11
siriusdevs/oop_7-1_2022 pull request #12
Opened 2022-11-08 10:00 UTC by nazaroviktor2

@siriusdevs

2022-11-09 19:09 UTC, siriusdevs requested changes

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/__init__.py
> +"""Init file."""
Это что за файл с комментариями?

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/geometric_shapes.py
> +from .exeptions import UnrealTriangleError
exCeptions

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/exeptions.py
> +"""A few exceptions."""
в комментарии exceptions (правильно), а файл называется exeptions

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/exeptions.py
> +class UnrealTriangleError(Exception):
InvalidTriangleError? InvalidTriangleSides?

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/__init__.py
> +"""Init file."""
я понимаю, зачем в его сделали, но если он пустой, это подозрительно, как считаете?

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/geometric_shapes.py
> +            ValueError: if some sides not be float
if any of the sides is not float

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/geometric_shapes.py
> +        # проверка треугольника на существование
eto chto russkiy?

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/models/geometric_shapes.py
> +        return round(math.pi * self.radius ** 2, 2)
остальное понравилось, молодец! :+1:

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/test_geometric_shapes.py
> +    assert triangle.side_a == side_a
знаете, в чём тут проблема? эти 3 assert считаются за один тест. если первый будет false, остальные два не выполняются.  в данном случае это правильно, пожалуй, но на будущее обязательно имейте ввиду.

2022-11-09 19:09 UTC, siriusdevs commented on 01-11/test_geometric_shapes.py
> +    assert circle.radius == radius
assert Circle(radius).radius == radius ??

2022-11-09 19:09 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS504,WPS112,WPS614,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,S311,WPS337
не увлекайтесь, я слежу за вами :eyes: 
на этот раз ничего криминального, прощаю.

2022-11-09 19:23 UTC, siriusdevs commented
#7 @nazaroviktor2 :timer_clock:

2022-11-10 07:19 UTC, nazaroviktor2 commented on setup.cfg
> +ignore=Q000,WPS433,WPS504,WPS112,WPS614,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,S311,WPS337
eto chto russkiy?  :eyes:

2022-11-10 07:19 UTC, nazaroviktor2 commented on 01-11/models/geometric_shapes.py
> +        return round(math.pi * self.radius ** 2, 2)
🥰🥰🥰

2022-11-10 20:12 UTC, siriusdevs approved these changes

2022-11-10 20:12 UTC, merged