Vechernina 01-11
siriusdevs/oop_7-1_2022 pull request #17
Opened 2022-11-10 11:25 UTC by vecherninanika

2022-11-10 20:30 UTC, siriusdevs requested changes

2022-11-10 20:30 UTC, siriusdevs commented on classtriangle.py
> +        p = (self.side1 + self.side2 + self.side3) / 2
у вас есть self.perimeter()  для этого, не дублируйте код

2022-11-10 20:30 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,WPS111,WPS114
не увлекайтесь добавлением ошибок в исключения. это ок, можете оставить

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +    assert new_triangle.area() == res
assert Triangle(side1, side2, side3).area() == res
??
:roll_eyes:

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +    assert new_circle.radius() == radius
Circle(radius).radius
??

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +    new_circle = Circle(radius)
здесь тоже

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +@pytest.mark.parametrize('radius, res', circle_inp)
parametrize для одного теста?

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +@pytest.mark.parametrize('radius, res', circle_inp)
parametrize для одного теста?

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +@pytest.mark.parametrize('side1, side2, side3, res', triangle_inp_area)
parametrize для одного теста?

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +@pytest.mark.parametrize('side1, side2, side3, res', triangle_inp_perimeter)
parametrize для одного теста?

2022-11-10 20:30 UTC, siriusdevs commented on test_circle_triangle.py
> +@pytest.mark.parametrize('side1, side2, side3', triangle_inp_sides)
parametrize для одного теста?

2022-11-10 20:30 UTC, siriusdevs commented on classtriangle.py
> +                return i
это что такое?? 
подбор корня среди целых чисел??
есть value ** 0.5
есть math.sqrt, в конце концов
зачем это?

2022-11-12 17:52 UTC, vecherninanika commented
Добрый вечер! Я исправила все ошибки.

2022-11-13 19:09 UTC, siriusdevs requested changes
В методах, округляющих значение на выходе, нужно это добавлять в описание. В остальном всё ок

2022-11-13 19:09 UTC, siriusdevs commented on classcircle.py
> +        return round(2 * math.pi * self.radius, 2)
в описании всех методов, которые округляют значение на выходе, нужно добавлять это в описании - это очень важно!

2022-11-15 18:00 UTC, siriusdevs approved these changes

2022-11-15 18:00 UTC, merged