Added checker to figures and custom exception
siriusdevs/oop_7-1_2022 pull request #18
Opened 2022-11-10 12:14 UTC by Max2288

2022-11-10 20:43 UTC, siriusdevs requested changes
_Disappointing_

2022-11-10 20:43 UTC, siriusdevs commented on figures.py
> +                if self.side2 + self.side3 > self.side1:
а если бы хранили в списке, как я просил, было бы проще. 
если бОльшая сторона меньше суммы двух остальных, то и остальные ОК

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +    assert tr.is_valid() == expectation
Triangle(side1, side2, side3).is_valid() == expectation
??
:roll_eyes:

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +    tr.is_valid()
1) тоже можно записать в 1 строку
2) где assert?? :no_good:

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +    cr.is_valid()
????????????????????????????????

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +    assert cr.is_valid() == expectation
??

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +test_triangle_square = [(1.0, 1.0, 1.0, 0.4330127018922193), (3.0, 4.0, 5.0, 6.0)]
делайте или округеление в методе (что правильно), или pytest approx.если не разберетесь, спросите у @annashutova

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
>  @pytest.mark.parametrize('side1, side2, side3, expect', test_triangle_square)
docstring "test for it"???

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +    """Test for it.
test for it?????for whatt???????????????

2022-11-10 20:43 UTC, siriusdevs commented on test_main.py
> +    """Test for it.
test for itt??????????for whattt?????????????

2022-11-13 19:49 UTC, Max2288 commented
Исправил всё в соответсвии с review

2022-11-15 18:35 UTC, siriusdevs requested changes
нигде нет проверки на то, число записывается в свойства или нет. тесты тоже это не проверяют. зачем нужен круг, в который можно вместо  радиуса записать 'котопёс'? зачем нужны тесты, которые это не проверяют?

2022-11-17 09:21 UTC, siriusdevs approved these changes

2022-11-17 09:21 UTC, merged