Добавлено ДЗ за 01.11.22.
siriusdevs/oop_7-1_2022 pull request #20
Opened 2022-11-12 07:17 UTC by blinmakersha

2022-11-13 19:03 UTC, siriusdevs requested changes
+ служебные файлы (.DS_store) явно должны быть в git ignore!

2022-11-13 19:03 UTC, siriusdevs commented on 01-11/test_task1.py
> +    assert circle.radius == radius
посмотрите на свои 52 и 61 строку и подумайте, что тут можно упростить :)

2022-11-13 19:03 UTC, siriusdevs commented on 01-11/test_task1.py
> +check_triangle_perimeter = [(3, 4, 5, 12), (13, 20, 15, 48), (3.45, 4.53, 5.34, 13.32)]
не слишком длинные названия переменных? 24 символа

2022-11-13 19:03 UTC, siriusdevs commented on 01-11/task01.py
> +        return round(res, 2)
в описании метода нигде не написано, что он округляет числа до 2 знака, а это важно!

2022-11-13 19:03 UTC, siriusdevs commented on 01-11/task01.py
> +        res = (s_per * (s_per - self.side1) * (s_per - self.side2) * (s_per - self.side3)) ** 0.5
в описании метода нигде не написано, что он округляет числа до 2 знака, а это важно!

2022-11-13 19:03 UTC, siriusdevs commented on 01-11/task01.py
> +    def length(self):
в описании метода нигде не написано, что он округляет числа до 2 знака, а это важно!

2022-11-13 19:03 UTC, siriusdevs commented on 01-11/task01.py
> +    def area(self):
в описании метода нигде не написано, что он округляет числа до 2 знака, а это важно!

2022-11-14 20:13 UTC, blinmakersha commented
Исправила все ошибки.

2022-11-15 17:57 UTC, siriusdevs approved these changes
так и не поменяли места вроде
_circle = Circle(radius)
assert circle.area() == area_
на
_assert Circle(radius).area() == area_

будем считать, что на будущее вы это поняли. остальное ок

2022-11-15 17:57 UTC, merged