HW 01-11 | 09-11
siriusdevs/oop_7-1_2022 pull request #21
Opened 2022-11-12 15:37 UTC by radugaboost

@siriusdevs

2022-11-13 18:47 UTC, siriusdevs commented
у вас не активированы actions в вашем репозитории. я не вижу, прошли тесты и линтер или нет.

2022-11-13 18:48 UTC, siriusdevs requested changes
нет проверки тестов и линтера - не активированы в вашей ветке. зайдите в actions и активируйте их

2022-11-15 20:15 UTC, radugaboost commented
@siriusdevs

2022-11-20 15:34 UTC, siriusdevs requested changes

2022-11-20 15:34 UTC, siriusdevs commented on main.py
> +class NotValidTriang(Exception):
объявление класса пустое, pass тоже нет. если IDE это не подчеркивает, это ещё не значит, что это ок.

2022-11-20 15:34 UTC, siriusdevs commented on main.py
> +    """There is no such circle."""
:eyes:

2022-11-20 15:34 UTC, siriusdevs commented on main.py
> +        if not isinstance(self.radius, (float)):
радиус не может быть int?

2022-11-20 15:34 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,WPS531,WPS432
WPS 531 вам говорит о ваших странных if и возвращаемых значениях. Может, это лучше исправить?
WPS 432 magic numbers тоже не ок

2022-11-20 15:34 UTC, siriusdevs commented on test_main.py
> +    assert Triangle(-1.0, 3.1, 3.1).is_valid()
Есть проверка на нормальные, есть на отрицательные. Где проверка на 0 ? Где проверка на то, что можно построить треугольник из таких 3 сторон?

2022-11-22 10:27 UTC, siriusdevs requested changes

2022-11-22 10:27 UTC, siriusdevs commented on main.py
> +
Это плохо, потому что это дублирование кода. Этот класс отличается от класса ошибки треугольника одним словом. Пусть будет один класс, который принимает фигуру при инициализации.

2022-11-22 10:27 UTC, siriusdevs commented on main.py
> +        return True
if A return False
return True

может, сразу
return not A???

2022-11-22 10:27 UTC, siriusdevs commented on test_main.py
> +    assert circle.length() == answer
почему нельзя это в одну строчку написать?

2022-11-22 10:27 UTC, siriusdevs commented on test_main.py
> +    assert circle.radius == radius
почему нельзя это в одну строчку написать?

2022-11-22 21:42 UTC, siriusdevs requested changes

2022-11-22 21:42 UTC, siriusdevs commented on main.py
> +            if not isinstance(side, (float, int)):
вместо for - if используйте all

2022-11-22 21:56 UTC, radugaboost commented
@siriusdevs I'm tired

2022-11-23 08:02 UTC, siriusdevs approved these changes
В будущем жду от вас более информативных названий коммитов, чем "fixed bugs", "fixed again" и тд.
И почему в файле readme просто фраза don't read me?
И что касается усталости - можно всё делать нормально с первого раза и не придётся исправлять кучу раз :) Понимаю, что это сложно, но вы же учитесь!

2022-11-23 08:02 UTC, merged