Домашка за первое ноября
siriusdevs/oop_7-1_2022 pull request #23
Opened 2022-11-14 11:48 UTC by KatyaGotskina

2022-11-15 18:22 UTC, siriusdevs requested changes

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/circles_and_triangles.py
> +        return round(self.radius ** 2 * pi, 3)
Если добавляете округление, нужно это писать в docstring. Вы же не возвращаете точный float, вы его округляете? Пользователь вашего класса должен это знать извне. Так во всех методах с округлением - не буду дублировать комментарий

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/circles_and_triangles.py
> +                return True
if self.radius > 0: return True
то есть, если радиус больше нуля, это if True return True. А если нет, то придём в return False :smiley:

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/circles_and_triangles.py
> +                    if fir + sec > th and sec + th > fir and fir + th > sec:
if True return True if False return False

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/test_circle.py
> +    assert circle.radius == radius
16-17: assert Circle(radius).radius == radius

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/test_circle.py
> +    assert circle.is_valid() == res
assert True == True :smiley:

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/test_circle.py
> +    assert circle.is_valid() == res
я бы понял, если бы были тесты разные. но у вас все тесты на True

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/test_circle.py
> +    assert circle.area() == area
46-47: Circle(radius).area() == area

2022-11-15 18:22 UTC, siriusdevs commented on Homework_0111/test_circle.py
> +    assert circle.area() == area
дальше так тоже везде, не буду дублировать.  Думаю, смысл понятен.

2022-11-15 18:22 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,WPS420,WPS604,WPS231,E501,WPS220
E501 хотите поменять длину строки - меняйте тут, в setup. не надо это исключать из ошибок проверяемых

2022-11-15 18:22 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,WPS420,WPS604,WPS231,E501,WPS220
зачем исключать WPS604?

2022-11-20 16:55 UTC, siriusdevs requested changes

2022-11-20 16:55 UTC, siriusdevs commented on setup.cfg
> +max-line-length = 170
max 119

2022-11-20 16:55 UTC, siriusdevs commented on Homework_0111/circles_and_triangles.py
> +        if isinstance(fir, (int, float)) and isinstance(sec, (int, float)):
используйте функцию all

2022-11-20 16:55 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,WPS420,WPS604,WPS231,WPS220
WPS220 не надо исключать. слишком глубокое ветвление - это плохо

2022-11-22 10:35 UTC, siriusdevs requested changes

2022-11-22 10:35 UTC, siriusdevs commented on Homework_0111/circles_and_triangles.py
> +        return round(self.radius ** 2 * pi, 3)
а где тип возвращаемого значения? может, вы хотели написать returns float? а потом уже описание

2022-11-23 16:53 UTC, siriusdevs requested changes
У вас не активированы workflows в репозитории.. я не вижу, проходят ли тесты и проверка линтера

2022-11-26 10:43 UTC, KatyaGotskina commented
При проверке flake8 с помощью командной строки всего репозитория никаких ошибок не выводит, однако проверку линтера на гитхабе не проходит

2022-11-26 10:50 UTC, KatyaGotskina commented
При обновлении flake8 на компьютере перестали выводиться ошибки, которые выводятся при проверке линтера. Что тут можно сделать?

2022-11-26 18:33 UTC, siriusdevs reviewed
у вас в pylint.yml вашего workflows указан flake8==3.9.0, а на компьютере у вас другой. всё просто - нужно привести линтер в репозитории в соответствие с комьютером.

2022-12-02 19:48 UTC, siriusdevs requested changes
1. Очень неудобное текстовое меню. Меню должно быть пунктами и цифрами, чтобы ничего не нужно было вводить вручную.
2. почему нельзя посмотреть информацию о здании? я вижу его на карте, но как узнать его свойства?

код буду смотреть после внесения правок.

2022-12-07 06:23 UTC, KatyaGotskina commented
Все ошибки исправлены, дома на карте отмечаются крестиками, можно смотреть информацию о здании. Остался вопрос только по pytest, который должен выполняться в конкретной папке

2022-12-08 11:33 UTC, KatyaGotskina commented
Все получилось с тестами! Теперь все работает как надо. Галочка есть

2022-12-11 21:18 UTC, siriusdevs requested changes
я добавил здание на координаты 0,0 и он встал в левый нижний угол.

2022-12-16 15:16 UTC, KatyaGotskina commented
дело в том, что я рассчитываю на пользователя, который не считает индекс первого элемента нулевым. Поэтому для добавления здания в верхний правый угол необходимо использовать координаты 1 1

2022-12-18 17:45 UTC, siriusdevs commented
> дело в том, что я рассчитываю на пользователя, который не считает индекс первого элемента нулевым. Поэтому для добавления здания в верхний правый угол необходимо использовать координаты 1 1

в верхний левый ,наверно :laughing: ну ладно

2022-12-18 20:53 UTC, siriusdevs requested changes
В зданиях исправляйте, потом наверняка ещё что-то найду..

Барберы выглядят ок, приносите защищать

2022-12-18 20:53 UTC, siriusdevs commented on Homework_2211/buildWorker.py
> +            if all([isinstance(self.floors, int), isinstance(self.coord_x, int), isinstance(self.coord_y, int)]):
включение

2022-12-18 20:53 UTC, siriusdevs commented on Homework_2211/buildWorker.py
> +                return all([self.floors > 0, self.width > 0, self.height > 0])
включение

2022-12-18 20:53 UTC, siriusdevs commented on Homework_2211/test_town.py
> +    assert buildWorker.Building(name, height, width, floors, coord_x, coord_y).name == name
:crying_cat_face: 
building = buildWorker.Building(name, height, width, floors, coord_x, coord_y)
for attr, value in tests: assert getattr(building, attr) == value

:running_man:

2022-12-18 20:53 UTC, siriusdevs commented on Homework_2211/test_town.py
> +    assert buildWorker.Map(length, width).length == length
зачем два раза создавать карту опять?

2022-12-18 20:53 UTC, siriusdevs commented on Homework_2211/user.py
> +                                print(str(place).ljust(6), end=' ')
тут глубина уже 9... может, что-то стоило вынести в отдельные функции?

2022-12-21 19:57 UTC, siriusdevs approved these changes

2022-12-21 19:59 UTC, merged