Homework 09-11-2022
siriusdevs/oop_7-1_2022 pull request #24
Opened 2022-11-15 15:47 UTC by kirillsev1

2022-11-15 18:11 UTC, siriusdevs requested changes

2022-11-15 18:11 UTC, siriusdevs commented on 0111_Pr/main.py
> +        if not isinstance(self.radius, int | float) or self.radius_check():
В Triangle метод check возвращает True если всё ок, а  в Circle метод check возвращает True, если всё плохо?
_Программирование, уровень 99_

2022-11-15 18:11 UTC, siriusdevs commented on 0111_Pr/main.py
> +        if not isinstance(self.first & self.second & self.third, int | float) or not self.sides_check():
self.first & self.second & self.third выглядит впечатляюще
_print(1 & 2 & 3)
0_
ну да, ноль это int, проверка успешная

2022-11-15 18:11 UTC, siriusdevs commented on 0111_Pr/main.py
> +        if not isinstance(self.first & self.second & self.third, int | float) or not self.sides_check():
и где проверка, что они больше нуля? или стороны могут быть отрицательными у вас почему-то?

2022-11-16 06:22 UTC, kirillsev1 commented on 0111_Pr/main.py
> +        if not isinstance(self.first & self.second & self.third, int | float) or not self.sides_check():
Проверка, что стороны больше 0 в методе sides_check()

2022-11-16 18:57 UTC, siriusdevs requested changes

2022-11-16 18:57 UTC, siriusdevs commented on 0111_Pr/main.py
> +        if not isinstance(self.first * self.second * self.third, int | float) or not self.sides_check():
Если в аттрибуте не число, а объект типа, для которого не прописан знак умножения, будет ошибка. А не знаете вы об этом, потому что теста на это нет.

2022-11-20 16:58 UTC, siriusdevs requested changes

2022-11-20 16:58 UTC, siriusdevs commented on 0111_Pr/main.py
> +        if not isinstance(self.first & self.second & self.third, int | float) or not self.sides_check():
нет у вас нигде проверки на "больше 0". 
в init у вас проверка на int|float, в sides_check проверка на то, что сумма любых двух больше любой третьей

2022-11-22 10:37 UTC, siriusdevs approved these changes

2022-11-22 10:46 UTC, merged