ну типо домашка, даже без анекдота :(
siriusdevs/oop_7-1_2022 pull request #27
Opened 2022-11-20 16:53 UTC by rtrwslv

2022-11-20 18:38 UTC, siriusdevs commented
у вас не работают workflows, я не вижу, проходят ли тесты и линтер. нужно активировать в actions

2022-11-21 21:02 UTC, rtrwslv commented
- Доктор, я себя чувствую, как C++.
- Это как?
- Меня все боятся, говорят, что я больше не нужен и ненавидят...

2022-11-22 11:00 UTC, siriusdevs requested changes
1) нет комментариев и docstrings. дальше даже не смотрел
2) вам точно нужен setup.cfg на 258 строк?

2022-11-22 11:00 UTC, siriusdevs commented on figures.py
> +        self.sides = sides
при инициализации принимаем любые sides, получается?

2022-11-22 11:00 UTC, siriusdevs commented on figures.py
> +    def sides(self, s):
нигде нет docstrings, во всем домашнем

2022-11-29 20:40 UTC, rtrwslv commented
Стоят старая и молодая профурсетка на боевом посту. Старая все объясняет - к кому подходить, к кому не надо... На рассвете вдруг из дверей оффиса нетвердой походкой выходит мужик, волосы взъерошены, глаза красные... Молодая: - Ой, что это с ним? Старая: - Не обращай внимания. Это свой, программист. Тоже всю ночь докстринги писал.

2022-11-29 20:41 UTC, rtrwslv commented
Стоят старая и молодая проститутки на боевом посту. Старая все объясняет - к кому подходить, к кому не надо... На рассвете вдруг из дверей оффиса нетвердой походкой выходит мужик, волосы взъерошены, глаза красные... Молодая: - Ой, что это с ним? Старая: - Не обращай внимания. Это свой, программист. Тоже всю ночь докстринги писал.

2022-11-29 20:41 UTC, rtrwslv commented
Стоят старая и молодая проститутки на боевом посту. Старая все объясняет - к кому подходить, к кому не надо... На рассвете вдруг из дверей оффиса нетвердой походкой выходит мужик, волосы взъерошены, глаза красные... Молодая: - Ой, что это с ним? Старая: - Не обращай внимания. Это свой, программист. Тоже всю ночь докстринги писал.

2022-11-29 20:41 UTC, rtrwslv commented
Стоят старая и молодая профурсетки на боевом посту. Старая все объясняет - к кому подходить, к кому не надо... На рассвете вдруг из дверей оффиса нетвердой походкой выходит мужик, волосы взъерошены, глаза красные... Молодая: - Ой, что это с ним? Старая: - Не обращай внимания. Это свой, программист. Тоже всю ночь докстринги писал.

2022-12-11 20:57 UTC, siriusdevs commented
Что смешнее - студент, отправляющий мне анекдоты, или его 0 сданных домашних заданий?

2022-12-11 21:14 UTC, siriusdevs requested changes

2022-12-11 21:14 UTC, siriusdevs commented on setup.cfg
> +  WPS615  # FIXME: unpythonic setter/getter
это что за хрень?
может, мне это кажется?
может, мне это снится?
вы с ума сошли? это вообще что такое?

у меня нет слов.

2022-12-13 13:28 UTC, siriusdevs requested changes

2022-12-13 13:28 UTC, siriusdevs commented on figures.py
> +        return sum(self.sides)
Треугольник со сторонами .2 .2 .2 вернёт периметр 0.60000000000000001

2022-12-13 13:34 UTC, siriusdevs approved these changes
мне не понравилось :crying_cat_face:

2022-12-21 19:35 UTC, siriusdevs commented
у вас конфликт @rtrwslv

2023-01-09 08:10 UTC, siriusdevs requested changes
у вас нет в репозитории домашней 22-11, что я должен проверить?

2023-01-30 17:50 UTC, merged