Vnesterov
siriusdevs/oop_7-1_2022 pull request #28
Opened 2022-11-20 16:53 UTC by nester256

2022-11-20 16:54 UTC, nester256 commented
Complite homework

2022-11-20 18:26 UTC, siriusdevs commented
У вас не работают workflows, я не вижу, проходят ли тесты и линтер. Нужно их активировать в actions

2022-11-21 08:14 UTC, nester256 commented
Add workflows

2022-11-22 10:55 UTC, siriusdevs requested changes
В PR с кругом и треугольником 16 файлов. Зачем мне ваши pycache? вообще не понятно
Код отдельных геттеров и сеттеров на каждую сторону треугольника - ужасен.
Добавление всех ошибок flake8 в исключения - наглость. 


Переделывайте

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/circle.py
> +        if not isinstance(radius, (float, int)):
дублирование кода. вы можете здесь вызвать свой метод сеттера. если будут проблемы, он вызовет ошибку

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/circle.py
> +        This function returns the length of a circle. / Данная функция возвращает длину окружности
в docstring не написано про округление

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/circle.py
> +        This function returns the square of a circle. / Данная функция возвращает площадь окружности
в docstring не написано про округление

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/exeptions_for_triangle.py
> +        Exception for create triangle. \
В многострочном комментарии не нужны переносы строк

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +            raise TriangleInvalidSides([a, b, c])
это опять огромное дублирование

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +            raise TriangleInvalidSides([self.__a, self.__b, new_c])
ужас, property getter + setter на каждую сторону??
а если у вас будет многоугольник?? количество строк кода будет зависеть от количества сторон? и везде будет повторяться один и тот же код?

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        return self.__a + self.__b + self.__c
0.3 + 0.2 + 0.2 != 0.7 потому что будет 0.700000000000001

2022-11-22 10:55 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +                           (half_perimetr - self.__b) * (half_perimetr - self.__c))
в docstring не написано про округление

2022-11-22 10:55 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS504,WPS112,WPS614,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,S311,WPS337,D100,WPS111,DAR10
это наглость. вы сколько кинули ошибок в исключения? 500?

2022-11-30 12:40 UTC, nester256 commented
Исправил ошибки

2022-12-06 18:17 UTC, siriusdevs requested changes

2022-12-06 18:17 UTC, siriusdevs commented on setup.cfg
> +max-line-length = 150
слишком много

2022-12-06 18:17 UTC, siriusdevs commented on setup.cfg
> +ignore=Q000,WPS433,WPS407,C819,WPS306,I00,WPS300,E800,D106,WPS226,WPS360,C812,D401,WPS115,DAR201,N400,WPS317,E502,WPS202,WPS221,WPS318,WPS301,RST210,WPS111,WPS114,D205,DAR101,DAR401,RST301,WPS231,DAR
всё равно много в исключениях, многие wps ошибки легко исправить

2022-12-06 18:17 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        This method creates a triangle.
если в init на одну строку висит docstring на 15 строк, это явно проблема :smile:

2022-12-06 18:17 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        """
похожая ситуация

2022-12-06 18:17 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +import math
целый модуль для использования sqrt? 
можно импортировать из него только sqrt, не говоря уже о том, что можно просто возвести в степень 0.5

2022-12-08 20:25 UTC, nester256 commented on Homework_1.11.22/triangle.py
> +        """
А что там лишнего написано?

2022-12-08 21:45 UTC, nester256 commented
#Я не нашёл как их править W503,W504,WPS337.

2022-12-11 21:21 UTC, siriusdevs commented
W503 - бесполезный else, возвращающий значение
W504 - можете оставить.
WPS337 - многострочное условие в if. 

Это так сложно исправить?

2022-12-11 21:23 UTC, siriusdevs commented
У вас 44 коммита в репозитории. Судя по названиям, несколько коммитов вы переименовывали файлы, а потом 40 коммитов правили ошибки оформления.

Не умеете делать лаконичные коммиты - делайте rebase.
Сейчас у вас из 44 названий примерно 2 - информативные

2022-12-11 21:33 UTC, siriusdevs requested changes

2022-12-11 21:33 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +            half_perimetr * (half_perimetr - self.sides[0])
собираюсь использовать переменную 4 раза в одной строке, назову её в 13 символов?

2022-12-11 21:33 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        Устанавливает новые стороны.
Во всех докстрингах нет пропущенной строчки после описания. Сразу видно, что эту ошибку оформления добавили в исключения flake вместо того, чтобы просто оформить нормально

2022-12-11 21:33 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        if not isinstance(side_a, (float, int)) \
как насчёт использовать all??????????????????????????

2022-12-11 21:33 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        return True
if not condition:
return True


как насчёт вынести условия и вернуть сразу условие?

2022-12-11 21:33 UTC, siriusdevs commented on Homework_1.11.22/triangle.py
> +        """
чего лишнего написано?

ну, например русский и английский варианты в одном месте?? давайте ещё китайский допишем, а то вдруг?
в ините "десятичная или целочисленная сторона". десятичное число - это число в двоичной системе счисления. бесполезный комментарий, ещё и ложная дихотомия.
side_a: float First side.
десятичное число - Первая сторона.
side_b: float Second side.
десятичное число - Вторая сторона.
и т.д....
как насчёт сделать sides : list ? кому нужны названия side_a side_b side_c если они **_нигде_** не используются?

2022-12-13 06:25 UTC, nester256 commented on Homework_1.11.22/triangle.py
> +        """
Я не понимаю чем вам не нравятся русские комментарии. Я их сделал для лучшего понимания кода, так как сам знаю английский плохо

2022-12-13 09:08 UTC, nester256 commented
поправил ошибки

2022-12-13 13:24 UTC, siriusdevs approved these changes

2022-12-13 13:25 UTC, merged