Vylkov
siriusdevs/oop_7-1_2022 pull request #29
Opened 2022-11-23 11:37 UTC by KabeSai

Добавил первое домашнее задание.

2022-11-23 17:10 UTC, siriusdevs requested changes
у вас ещё и проверка линтера не проходит, как и тесты. вас красный крестик на репозитории не смутил?

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +    """This is a projection of a triangle."""
проекция?

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +            raise NoneExistentFigure(sides)
тогда уже не NoneExistent, а Nonexistent

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +        """Initialization method.
может, лучше написать в описании, что это список из трёх сторон? зачем в описании init писать, что это метод инициализации?

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +        p = Triangle([self.side_1, self.side_2, self.side_3]).perimeter()*0.5
метод в существующем треугольнике создаёт ещё один такой же треугольник, чтобы посчитать периметр?? а у текущего треугольника никак нельзя проверить периметр??

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +                if sides[0] + sides[1] > sides[2]:
не проверили, что это числа, а уже складываете и сравниваете.

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +                print("Сторонами треугольника должны быть числа!")
PEP 20 Python zen Line 10: Errors should never pass silently.

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +                print("Сторонами треугольника должны быть числа!")
возможно, вы скажете, что у вас на случай, что стороны не являются числа, есть этот try except. но явная проверка на isinstance гораздо лучше, чем глушить ошибку, а потом возвращать в другое место false, который всё-таки вызовет ошибку

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +        """Initalization method.
То же самое с описанием

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +    def isvalid(self, radius: float) -> bool:
зачем self, если radius? зачем radius, если self?

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +            radius = radius * 1
i s i n s t a n c e

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/test_HW_01.py
> +    assert Triangle(sides).isvalid(sides) == expectation
вас тут не смущает Triangle(sides).isvalid(sides) ??? :smiley: 
почему-то приходится стороны два раза передавать))

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/test_HW_01.py
> +    assert Circle(radius).isvalid(radius) == expectation
то же самое

2022-11-23 17:10 UTC, siriusdevs commented on README.md
> +⣿⣯⣽⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿\n
?????????????????????????????????????????????????????????????????

2022-11-23 17:10 UTC, siriusdevs commented on HomeWork/HW_01.py
> +        """Initialization method.
описание

2022-11-23 21:10 UTC, KabeSai commented
Починил Линтеры и изменил код в соответсвии с выделиными ошибками

2022-11-26 18:45 UTC, siriusdevs requested changes

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/homework_first.py
> +        """This method takes a list of parties and remembers them.
party в смысле "сторона" имеется ввиду при заключении договоров, например. у вас ведь уже используется правильное слово sides, зачем всё переиначивать?

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/homework_first.py
> +                    print("С сторонами такой длины треугольника не существует!")
сложно сказать, зачем нужны все эти принты.. без них всё было бы так красиво..

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/homework_first.py
> +        """This method calculates the circumference.
не написано про округление

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/homework_first.py
> +        """Calculates the area and rounds it to thousandths.
не написано про округление

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/homework_first.py
> +            return False
не понимаю, зачем здесь кортеж типов вынесен в отдельную строку.. также не понимаю опять, зачем вам все эти принты. без всего этого было бы 3 строки, а с этим - 6.
почему я недоволен принтами? да потому что этот метод вернёт false в init и вызовется ошибка. недостаточно информативно?

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/test_homework_first.py
> +                  ([6, "yeet", 5], False), ([-3, 4, 5], False)]
целых два теста на строки, а теста на 0 нет

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/test_homework_first.py
> +    assert Triangle(sides).isvalid(sides) == expectation
у вас isvalid теперь принимает только self. каким образом он теперь принимает sides в тестах? и как они проходят?

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/test_homework_first.py
> +    assert Circle(radius).isvalid(radius) == expectation
то же самое

2022-11-26 18:45 UTC, siriusdevs commented on HomeWork/test_homework_first.py
> +    assert Triangle(sides).isvalid() == expectation
а тут он уже работает с isvalid без аргументов?

2022-11-26 18:45 UTC, siriusdevs commented on README.md
> +Человек он рассеяный, но весьма добрый и дотошнй до кода, а ещё любит экспереминтировать!
эксперементировать -> экспериментировать
:smiley:

2022-11-26 19:15 UTC, KabeSai commented on README.md
> +Человек он рассеяный, но весьма добрый и дотошнй до кода, а ещё любит экспереминтировать!
Я не русский) Но русский люблю

2022-12-04 18:12 UTC, siriusdevs requested changes

2022-12-04 18:12 UTC, siriusdevs commented on HomeWork/homework_first.py
> +            if isinstance(sd[0], val_type) and isinstance(sd[1], val_type) and isinstance(sd[2], val_type):
all + включение + isinstance

2022-12-11 20:53 UTC, siriusdevs approved these changes

2022-12-11 20:54 UTC, merged