First homework
siriusdevs/oop_7-1_2022 pull request #3
Opened 2022-11-02 10:40 UTC by Max2288

2022-11-02 20:20 UTC, siriusdevs requested changes
Хороший код, но требуются исправления. Ознакомьтесь с review и внесите изменения.

2022-11-02 20:20 UTC, siriusdevs commented on figures.py
> +        """Initialization function.
В таких случаях можно делать однострочный docstring без указания всех аргументов. У вас получается избыточное комментирование - и так очевидно ,что делает init. Это не плохо, просто рекомендация на будущее. И да, это не функция. Это метод класса.

2022-11-02 20:20 UTC, siriusdevs commented on figures.py
> +    def perimetr(self) -> float:
perimeter

2022-11-02 20:20 UTC, siriusdevs commented on figures.py
> +    def __init__(self, radius: float) -> None:
Тут то же самое - на метод, состоящий из одной ультраочевидной строки, приходится куча строк docstring

2022-11-02 20:20 UTC, siriusdevs commented on test_main.py
> +@pytest.mark.parametrize('radius', test_circle_parametrs)
parametrize для запуска одного теста? :)

2022-11-02 20:20 UTC, siriusdevs commented on test_main.py
> +test_triangle_perimetr = [(1.0, 2.0, 3.0, 6.0), (0.1, 0.2, 0.3, 0.6000000000000001)]
Это неправильно и это нужно переделать. Вы не можете так проверять неточные вычисления в программировании. 
Ознакомьтесь со [ссылкой](https://docs.pytest.org/en/latest/reference/reference.html#pytest.approx)

2022-11-05 08:03 UTC, Max2288 commented
Исправил всё в соответсвии с review

2022-11-06 11:04 UTC, siriusdevs approved these changes

2022-11-06 11:04 UTC, merged