Страшно, очень страшно
siriusdevs/oop_7-1_2022 pull request #32
Opened 2022-11-27 20:25 UTC by Nirtkor

Мы не знаем что это такое, если бы мы знали что это такое, мы не знаем что это такое!

2022-11-27 20:42 UTC, siriusdevs requested changes
.DS_Store файл мне ваш тоже не нужен :))

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +            raise Exception("Такой треугольник не построить")
1) то, что в try - не работает. оно выведет ошибку, если это не числа. проверка на это у вас будет дальше. а если тут даже выйдет false, это не ошибка. и условие не выполнится
2) если ошибка, то вот сделай другую ошибку - плохой подход
3) вместо Exception используйте свою ошибку
4) структура плохая.. лучше бы вывели проверку в отдельный метод

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +        try:
дублирование кода, а это очень плохо. вот поэтому и надо было в отдельный метод это вытащить

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +        return (self.__sides[0] + self.__sides[1] + self.__sides[2])
0.3 + 0.2 + 0.2 == 0.700000001, к сожалению. надо округлять

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +            raise Exception("Неверный формат данных")
тоже дублирование кода

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +        """circle length calculation
не пишете в описании про округление

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +        """circle area calculation
не пишете в описании про округление

2022-11-27 20:42 UTC, siriusdevs commented on HW_1_OOP.py
> +        """calculating the area of a triangle
не пишете в описании про округление

2022-11-27 20:42 UTC, siriusdevs commented on test_HW_1_OOP.py
> +triangle_perimetr = [(Triangle(5, 5, 5), 15), (Triangle(9, 2, 5), 16), (Triangle(12, 10, 10), 32)]
добавьте тут числа со знаками после точки, увидите как в текущей реализации тесты не пройдут.

2022-11-27 20:42 UTC, siriusdevs commented on test_HW_1_OOP.py
> +    assert circle.radius == radius
assert Circle(radius).radius == radius ??

2022-12-12 08:11 UTC, Nirtkor commented
Исправил ошибки, хотелось бы знать, правильно ли все сделал.
Если все хорошо, почищу литер и будет счастье для первых двух ячеек таблицы

2022-12-13 11:41 UTC, siriusdevs requested changes

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +"""Module for combining data types
не нужно писать комментарии к импортируемым модулям, у вас на первой строчке только должен быть комментарий, который описывает этот модуль (питоновский файл)

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +    def sometriangleexception(self):
вам этот метод не нужен, он пустой

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +        pass
вам этот метод не нужен, он пустой

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +    pass
если есть метод в классе, класс не пустой и не нужен pass

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +        if not isinstance(sides[0] or sides[1] or sides[2], Union[float, int]):
all([isinstance(side, (float, int)) for side in sides])

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +        if not (sides[0] + sides[2] > sides[1] and
или делайте через all и включение, или проверяйте только то, что большая сторона меньше суммы двух остальных - на самом деле, этого достаточно

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +        if sides[0] <= 0 or sides[1] <= 0 or sides[2] <= 0:
тоже нужно использовать all, старайтесь не дублировать код

2022-12-13 11:41 UTC, siriusdevs commented on HW1/HW1.py
> +        self.__sides = sides
сначала checker, а потом уже записывайте sides

2022-12-14 18:37 UTC, siriusdevs approved these changes

2022-12-14 18:38 UTC, merged