22-11
siriusdevs/oop_7-1_2022 pull request #35
Opened 2022-12-08 16:16 UTC by annashutova

2022-12-11 20:19 UTC, siriusdevs commented
пытался запустить ваш код,
ModuleNotFoundError: No module named 'simple_term_menu'.
Исправьте и запросите ревью

2022-12-11 20:20 UTC, siriusdevs requested changes
from simple_term_menu import TerminalMenu
ModuleNotFoundError: No module named 'simple_term_menu'

2022-12-14 19:15 UTC, siriusdevs requested changes
Мне понравился ваш код, вы проделали замечательную работу!
Пожалуйста, исправьте указанные недочёты - и можно будет вешать на стену в рамочке.
Самое главное - не дублируйте информацию о зданиях в карте, в карте о карте и т.п.. Это очень плохо и потенциально ведёт к множеству ошибок

2022-12-14 19:15 UTC, siriusdevs commented on hw3/test_classes.py
> +        Building(3, 9, -10)
нет проверки на 0. при этом в вашей программе при вводе данных 0 выводится ошибка, что аргументы должны быть integers :eyes:

2022-12-14 19:15 UTC, siriusdevs commented on hw3/maps/map0.json
> +            0,
такой формат (во всех картах) плох по нескольким причинам:
1) зачем хранить map_list, если его можно генерировать? это займёт мало времени. координаты домов есть в их данных, а размер двумерного списка есть в длине и ширине.
2) зачем хранить строку про каждое здание, если эта информация есть в файлах про здание? в buildings должны быть записи типа 0 : building_0.json
3) файл карты не читаемый и слишком большой.

2022-12-14 19:15 UTC, siriusdevs commented on hw3/main_prog.py
> +            print('There is nothing to delete.')
было бы замечательно, если бы на разных уровнях меню можно было передумать и выйти через q.
слишком часто я хочу выйти, но не могу - вынужден выполнять задуманные действия до конца.

2022-12-21 19:46 UTC, siriusdevs commented
`0 -- Create map
1 -- Choose map
2 -- Quit
Choose option: 1
Available maps:

map2

Traceback (most recent call last):
  File "/home/sirius/shutova/oop_7-1_2022/hw3/main_prog.py", line 151, in <module>
    curr_map = choose_map()
               ^^^^^^^^^^^^
  File "/home/sirius/shutova/oop_7-1_2022/hw3/main_prog.py", line 57, in choose_map
    print(Map.from_dict(**kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sirius/shutova/oop_7-1_2022/hw3/building_map.py", line 108, in from_dict
    return cls(**kwargs)
           ^^^^^^^^^^^^^
TypeError: Map.__init__() got an unexpected keyword argument 'map_list'`

@annashutova  не могу посмотреть карты - вылетает ошибка

2022-12-21 20:04 UTC, annashutova commented
@siriusdevs, может вы себе не все изменения залили? потому что я еще меняла json файлы со зданиями и картами (старые удалила и добавила новые, исправленные). в моих новых файлах даже нет карты map2
просто у меня со всеми новыми изменениями все работает....

2022-12-21 20:20 UTC, siriusdevs approved these changes
удалил у себя вторую карту, всё теперь работает.
хорошая реализация, хорошие тесты.

2022-12-21 20:20 UTC, merged