HW | 3
siriusdevs/oop_7-1_2022 pull request #52
Opened 2023-01-15 13:47 UTC by radugaboost

@siriusdevs

2023-01-17 11:53 UTC, siriusdevs commented
как это проверить? из всех py файлов по названию ничего не подходит, main.py ничего не запускает, просто завершается сразу и не выводит ничего в терминал. в папке maps только json-файлы

2023-01-17 11:54 UTC, siriusdevs requested changes
что запускать? тут кроме тестов и json ничего нет

2023-01-17 12:19 UTC, nazaroviktor2 commented
> что запускать? тут кроме тестов и json ничего нет

До меня дошла информация, что нужно запустить testing.py

2023-01-18 06:23 UTC, siriusdevs approved these changes

2023-01-18 06:23 UTC, merged