Homework 01-11-2022
siriusdevs/oop_7-1_2022 pull request #8
Opened 2022-11-05 16:48 UTC by kirillsev1

2022-11-06 11:06 UTC, siriusdevs requested changes

2022-11-06 11:06 UTC, siriusdevs commented on 0111_Pr/main.py
> +            int: int - math result rounds up to 2 numbers after dot(sum of sides).
int : int ?)

2022-11-06 11:06 UTC, siriusdevs commented on 0111_Pr/main.py
> +            float: float - math result rounds up to 2 numbers after dot(Heron's formula).
float : float

2022-11-06 11:06 UTC, siriusdevs commented on 0111_Pr/main.py
> +        """Method gets three args."""
Может, будет уместнее написать, что это Triangle class initializer method и всё такое? про три аргумента из сигнатуры видно

2022-11-07 14:39 UTC, kirillsev1 reviewed
Я переписал комментарии к функиям

2022-11-09 19:25 UTC, siriusdevs commented
В следующий раз если ждёте новое review, нажимайте на кнопку re-request review.
Я даже не видел, что вы уже внесли изменения.

2022-11-09 19:26 UTC, siriusdevs approved these changes

2022-11-09 19:26 UTC, merged